### ISSUE TITLE
qBittorrent wiki

### ISSUE THREAD

**Issue by FranciscoPombal** [hrap1919/qbclient#1]
The correct place in the qBittorrent wiki for alternate WebAPI clients is here, https://github.com/qbittorrent/qBittorrent/wiki/List-of-unnoficial-WebAPI-clients, not the footer. Just posting to let you know I've made the appropriate changes.

**Comment by hrap1919** [comment]
Thanks a lot! And excuse me for the wrong placing! I do know the github site good. I did not see a possibility to change the page in the correct place, seeing only an option to change the footer.  Just found the "Edit" button.
