### ISSUE TITLE
savepath not honoring

### ISSUE THREAD

**Issue by MS-design-ui** [hrap1919/qbclient#3]
Hi!

I love this, but I am having an issue where the save path is NOT being sent.

qbadd -f ~/.torrent skip_checking=true paused=true savepath='/home/user/X/'

I have also tried savepath=/home/user/X/ savepath="/home/user/X/"

None of them sent, unfortunately.

Qbit = 4.3.3

**Comment by hrap1919** [comment]
I did not see a problem with savepath here. I hope you have no too. I just note that for bash the argument 
```savepath='/home/user/X/'```
is the same as
```'savepath=/home/user/X/'```.
The qbc does not parse it, passing it into '-F' option of curl as is.
